// Generated by tools/patterns.py --hardcode --program main_1305 from tools/addresses.toml, edit those and re-run instead of this file.
// Every value is a 13.0.5 offset from the start of the game's main module.

pub fn register_scene_table() -> usize {
    0x3723a90
}

pub fn unregister_scene_table() -> usize {
    0x3723e70
}

pub fn exit_active_scene() -> usize {
    0x3726af0
}

pub fn sequence_scene_ctor() -> usize {
    0x3724550
}

pub fn sequence_scene_dtor() -> usize {
    0x37246c0
}

pub fn scene_queue_push_front() -> usize {
    0x37266d0
}

pub fn menu_sequence_scene_on_enter() -> usize {
    0x2363730
}

pub fn menu_sequence_scene_push_main_menu() -> usize {
    0x235cb00
}

pub fn g_vtable_scene() -> usize {
    0x50b62f0
}

pub fn g_vtable_sequence_scene_ui() -> usize {
    0x50a1070
}

pub fn g_vtable_scene_init_code_parameter() -> usize {
    0x50a11c0
}

pub fn com_frame_set_title_text() -> usize {
    0x1af8e90
}

pub fn com_frame_set_title_format() -> usize {
    0x1af8c80
}

pub fn com_frame_set_scene_text() -> usize {
    0x1af90b0
}

pub fn com_frame_set_header_size() -> usize {
    0x1af60a0
}

pub fn com_frame_set_footer_message() -> usize {
    0x1af53d0
}

pub fn com_frame_show_frame() -> usize {
    0x1af8570
}

pub fn com_frame_build_show_frame_options() -> usize {
    0x1af5880
}

pub fn com_frame_colour_header() -> usize {
    0x1af5f00
}

pub fn com_frame_play_footer_help_anim() -> usize {
    0x1af5320
}

pub fn com_frame_set_footer_button() -> usize {
    0x1af6200
}

pub fn com_frame_refresh_footer_layout() -> usize {
    0x1af4610
}

pub fn menu_background_set_background() -> usize {
    0x1af2070
}

pub fn g_com_frame_holder() -> usize {
    0x532f840
}

pub fn layout_root_create() -> usize {
    0x3773200
}

pub fn layout_root_build_from_layout_arc() -> usize {
    0x32cbf30
}

pub fn layout_root_set_enable_input() -> usize {
    0x37760f0
}

pub fn layout_root_activate() -> usize {
    0x3775dc0
}

pub fn layout_root_destroy() -> usize {
    0x3773770
}

pub fn text_box_set_text_string() -> usize {
    0x37a28a0
}

pub fn msbt_get_by_label() -> usize {
    0x377a120
}

pub fn pane_set_text_format() -> usize {
    0x377a4a0
}

pub fn view_play_animation() -> usize {
    0x3778300
}

pub fn pane_restore_original_texture() -> usize {
    0x3779650
}

pub fn view_get_pane() -> usize {
    0x3776910
}

pub fn view_get_parts() -> usize {
    0x3776640
}

pub fn list_scroller_setup() -> usize {
    0x3781a20
}

pub fn list_scroller_set_current_index() -> usize {
    0x3783c10
}

pub fn list_scroller_refresh_visible_rows() -> usize {
    0x377cc80
}

pub fn button_selector_create() -> usize {
    0x3770b30
}

pub fn button_selector_setup_button() -> usize {
    0x37717d0
}

pub fn button_selector_select_button() -> usize {
    0x3771a80
}

pub fn button_selector_set_shortcut() -> usize {
    0x3771930
}

pub fn button_selector_config_set_default_callbacks() -> usize {
    0x337df20
}

pub fn sub_menu_ctor() -> usize {
    0x32d6000
}

pub fn sub_menu_attach() -> usize {
    0x32d6470
}

pub fn fade_in() -> usize {
    0x32e5a30
}

pub fn fade_out() -> usize {
    0x32e5bf0
}

pub fn fade_out_instant() -> usize {
    0x32e5e60
}

pub fn g_fade_manager_holder() -> usize {
    0x532f7c8
}

pub fn loading_list_queue() -> usize {
    0x323beb0
}

pub fn loading_list_wait() -> usize {
    0x323cb80
}

pub fn loading_list_free() -> usize {
    0x323b9e0
}

pub fn g_vtable_threaded_loading_list() -> usize {
    0x5181b40
}

pub fn popup_open() -> usize {
    0x32f29a0
}

pub fn g_popup_holder() -> usize {
    0x532f820
}

pub fn popup_populate_params() -> usize {
    0x32edf70
}

pub fn popup_open_from_params() -> usize {
    0x32f1bb0
}

pub fn texture_resource_construct() -> usize {
    0x37a31e0
}

pub fn res_texture_file_cast() -> usize {
    0x31100
}

pub fn texture_resource_setup_gpu() -> usize {
    0x37a2ea0
}

pub fn texture_resource_reset() -> usize {
    0x37a29b0
}

pub fn picture_set_texture_info() -> usize {
    0x379e9c0
}

pub fn swkbd_make_preset() -> usize {
    0x39c6b50
}

pub fn swkbd_set_header_text() -> usize {
    0x39c6b60
}

pub fn swkbd_set_guide_text() -> usize {
    0x39c6190
}

pub fn swkbd_set_initial_text() -> usize {
    0x39c6160
}

pub fn swkbd_get_required_work_buffer_size() -> usize {
    0x39c6b20
}

pub fn swkbd_show_keyboard() -> usize {
    0x39c69b0
}

pub fn je_aligned_alloc() -> usize {
    0x392e290
}

pub fn free_default() -> usize {
    0x392eb40
}
